BEGIN;

INSERT INTO destinations (city, country, activity, operator, email) VALUES
('Bangkok', 'Thailand', 'Temple of the Reclining Buddha (Wat Pho)', 'Bangkok', 'quotinerary@gmail.com'),
('Bangkok', 'Thailand', 'Cooking Classes','Bangkok', 'quotinerary@gmail.com'),
('Bangkok', 'Thailand', 'Temple of the Emerald Buddha (Wat Phra Kaew)', 'Bangkok', 'quotinerary@gmail.com'),
('Bangkok', 'Thailand', 'The Grand Palace','Bangkok', 'quotinerary@gmail.com'),
('Chiang Mai', 'Thailand', 'Cooking Classes', 'Chiang Mai', 'quotinerary@gmail.com'),
('Chiang Mai', 'Thailand', 'Elephant Farm', 'Chiang Mai', 'quotinerary@gmail.com'),
('Chiang Mai', 'Thailand', 'Tiger Farm', 'Chiang Mai', 'quotinerary@gmail.com'),
('Chiang Mai', 'Thailand', 'Spas', 'Chiang Mai', 'quotinerary@gmail.com'),
('Chiang Mai', 'Thailand', 'Wat Chedi Luang', 'Chiang Mai', 'quotinerary@gmail.com'),
('Chiang Mai', 'Thailand', '3D Art Museum', 'Chiang Mai', 'quotinerary@gmail.com'),
('London', 'England', 'British Museum', 'London', 'quotinerary@gmail.com'),
('London', 'England', 'National Gallery', 'London', 'quotinerary@gmail.com'),
('London', 'England', 'Tower of London', 'London', 'quotinerary@gmail.com'),
('London', 'England', 'V&A - Victoria and Albert Museum', 'London', 'quotinerary@gmail.com'),
('London', 'England', 'Big Ben', 'London', 'quotinerary@gmail.com'),
('London', 'England', 'Stonehenge', 'London', 'quotinerary@gmail.com'),
('Paris', 'France', 'Musee d Orsay', 'Paris', 'quotinerary@gmail.com'),
('Paris', 'France', 'Eiffel Tower', 'Paris', 'quotinerary@gmail.com'),
('Paris', 'France', 'Musee du Louvre', 'Paris', 'quotinerary@gmail.com'),
('Paris', 'France', 'Notre Dame Cathedral', 'Paris', 'quotinerary@gmail.com'),
('Paris', 'France', 'Luxembourg Gardens', 'Paris', 'quotinerary@gmail.com'),
('Singapore', 'Singapore', 'Gardens by the Bay', 'Singapore', 'quotinerary@gmail.com'),
('Singapore', 'Singapore', 'Singapore Mass Rapid Transit (SMRT)', 'Singapore', 'quotinerary@gmail.com'),
('Singapore', 'Singapore', 'National Orchid Garden', 'Singapore', 'quotinerary@gmail.com'),
('Singapore', 'Singapore', 'Singapore Botanic Gardens', 'Singapore', 'quotinerary@gmail.com'),
('Singapore', 'Singapore', 'Singapore Zoo', 'Singapore', 'quotinerary@gmail.com'),
('New York City', 'United States', 'Central Park', 'New York City', 'quotinerary@gmail.com'),
('New York City', 'United States', 'The National 9/11 Memorial & Museum', 'New York City', 'quotinerary@gmail.com'),
('New York City', 'United States', 'The Metropolitan Museum of Art', 'New York City', 'quotinerary@gmail.com'),
('New York City', 'United States', 'Top of the Rock Observation Deck', 'New York City', 'quotinerary@gmail.com'),
('New York City', 'United States', 'Broadway Show', 'New York City', 'quotinerary@gmail.com'),
('Istanbul', 'Turkey', 'Hagia Sophia Museum / Church (Ayasofya)', 'Istanbul', 'quotinerary@gmail.com'),
('Cappadocia', 'Turkey', 'Hot Air Balloon', 'Cappadocia', 'quotinerary@gmail.com'),
('Pamukkale', 'Turkey', 'Pamukkale', 'Pamukkale', 'quotinerary@gmail.com'),
('Ephesus', 'Turkey', 'Ephesus', 'Ephesus', 'quotinerary@gmail.com'),
('Dubai', 'United Arab Emirates', 'Dubai', 'Dubai', 'quotinerary@gmail.com'),
('Kuala Lumpur', 'Malaysia', 'Petronas Twin Towers', 'Kuala Lumpur', 'quotinerary@gmail.com'),
('Hong Kong', 'China', 'Hong Kong Skyline', 'Hong Kong', 'quotinerary@gmail.com'),
('Hong Kong', 'China', 'Victoria Peak (The Peak)', 'Hong Kong', 'quotinerary@gmail.com'),
('Hong Kong', 'China', 'Tian Tan Buddha (Big Buddha)', 'Hong Kong', 'quotinerary@gmail.com'),
('Hong Kong', 'China', 'Victoria Harbour', 'Hong Kong', 'quotinerary@gmail.com');

COMMIT;
